sudo: required

language: c

services:
  - docker

before_script:
  - docker build --tag devel -f Dockerfile.dev .

script:
  - docker create --name develcontainer devel
  - mkdir TaxonomyTools
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/TaxonomyTools-1.1.0/x/Accessions2TaxIds/build/Accessions2TaxIds/Accessions2TaxIds Accessions2TaxIds
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/TaxonomyTools-1.1.0/x/TaxIds2Text/build/TaxIds2Text/TaxIds2Text TaxIds2Text
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/TaxonomyTools-1.1.0/x/TaxIds2TreeCompare/build/TaxIds2TreeCompare/TaxIds2TreeCompare TaxIds2TreeCompare
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/TaxonomyTools-1.1.0/x/TaxIds2Tree/build/TaxIds2Tree/TaxIds2Tree TaxIds2Tree
  - docker cp develcontainer:/source/dist-newstyle/build/x86_64-linux/ghc-8.4.3/TaxonomyTools-1.1.0/x/TaxIdsDistance/build/TaxIdsDistance/TaxIdsDistance TaxIdsDistance
  - cp LICENSE TaxonomyTools
  - tar -cvzf TaxonomyTools.tar.gz TaxonomyTools


deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: "TaxonomyTools.tar.gz" 
  on:
    tags: true
