sudo: required

language: c

services:
  - docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --tag taxonomytools -f Dockerfile.dev .

script:
  - docker create --name develcontainer TaxonomyTools
  - docker images
  - mkdir TaxonomyTools
  - docker cp develcontainer:/Accessions2TaxIds Accessions2TaxIds
  - docker cp develcontainer:/TaxIds2Text TaxIds2Text
  - docker cp develcontainer:/TaxIds2TreeCompare TaxIds2TreeCompare
  - docker cp develcontainer:/TaxIds2Tree TaxIds2Tree
  - docker cp develcontainer:/TaxIdsDistance TaxIdsDistance
  - cp LICENSE TaxonomyTools
  - tar -cvzf TaxonomyTools.tar.gz TaxonomyTools
  - docker push $DOCKER_USERNAME/taxonomytools:$TRAVIS_TAG


deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: "TaxonomyTools.tar.gz" 
  on:
    tags: true
